FROM node:boron

OM ubuntu:16.04

RUN sudo apt-get update

#RUN useradd -ms /bin/bash newuser
#USER newuser

#Install app dependencies

#RUN sudo mkdir /home/newuser/cloudstoriesapp

#WORKDIR /home/newuser/cloudstoriesapp

#COPY package.json /home/newuser/cloudstoriesapp/package.json
#RUN npm install && npm cache clean

#COPY angular-src/package.json /home/newuser/cloudstoriesapp/angular-src/package.json
#RUN cd angular-src
#RUN npm install && npm cache clean

#COPY . /home/newuser/cloudstoriesapp/

#RUN sudo npm install && sudo nom install nodemon —-save
#RUN sudo cd angular-src; sudo npm install

# Make port 80 available to the world outside this container
#EXPOSE 4200
#EXPOSE 3000

#CMD [“nohup nodemon&”,”ng serve”]