---
- hosts: final
  sudo: yes
  tasks:
  apt:
    update_cache: yes

## installing mongodb
  - name: install curl
    apt-key: name: adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  - name: Configure Docker 
    command: echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
  - name: update apt
    command: sudo apt-get update
  - name: install mongodb-org
    command: sudo apt-get install -y mongodb
  - name: daemon-reload
    command: systemctl daemon-reload
  - name: keyserver
    command: systemctl start mongod
  - name: enable mongo
    command: systemctl enable mongod


# ## for installing docker
#   - name: install curl
#     apt: name=curl state=latest
#   - name: Configure Docker 
#     command:  apt-get update
#   - name: keyserver
#     command:  apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
#   - name: repo sdfsd
#     command:  apt-add-repository 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
#   - name: update apt 
#     command:  apt-get update
#   - name: docker-engine
#     command:  apt-cache policy docker-engine
#   - name: docker-engine install
#     command:  apt-get install -y docker-engine
#   - name: start docker
#     command:  systemctl status docker
#   - name: add user to group
#     command: usermod -aG docker ubuntu

# ## for test container
#   - name: web web-test
#     command: docker run -d --name web-test -p 80:8000 crccheck/hello-world