---
- name: Installing and configuring Docker
  hosts: all
  become: yes
  vars_files:
    - providers/other/vars/other_vars.yml
  vars:
    - ansible_python_interpreter: /usr/bin/python3
  roles:
    - { role: docker, tags: ["docker"] }

