---
- hosts: test
  sudo: yes
  tasks:
    - name: install curl
      apt: name=curl state=latest
   
    - name: Install dependencies
      apt: 
          name={{ item }} 
          update_cache=yes
      with_items: 
          - python-dev
          - python-setuptools

    - name: Install pip
      easy_install: 
          name=pip 

    - name: Install docker-py
      pip: 
          name=docker-py 
          state=present
          version=1.1.0  

    - name: Add docker apt repo
      apt_repository:
        repo='deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'
        state=present

    - name: Import the Docker repository key
      apt_key:
          url=https://apt.dockerproject.org/gpg
          state=present
          id=2C52609D

    - name: Create a docker group
      group: 
          name=docker 
          state=present

    - name: Add user(s) to docker group
      user: 
          name={{ item }} 
          group=docker 
          state=present
      with_items: docker_users
      when: docker_users is defined

    - name: Configure Docker 
      template: 
          src=default_docker.j2 
          dest=/default/docker 
          mode=0644 
          owner=root 
          group=root
      notify: restart docker

    - name: Ensure web based hello world container is running
      docker_container:
        name: web_hello_world
        image: tutum/hello-world
        ports:
          - 80:80

    - name: Install Docker package
      apt:
          name=docker-engine
          update_cache=yes