#!/usr/bin/python
import sys
import twitter
import requests
import json
import time
from twitter.ratelimit import RateLimit

#-----------------------------------------------------------------------
# Twitter API credentials 
#-----------------------------------------------------------------------

access_token = "128552890-KmiXK200XMqWjKhsrPq6cfHDyCP1WNGVcnvOqs4C"
access_token_secret = "wYRCm48ZNIwEW7t7PHLFRAo6F9JXrBYt6E0s28Z0DU0rw"
consumer_key = "2Akcp0bkBnpgr4nMpOaIPOVa0"
consumer_secret = "xmZ5NpbbqnLFsWCB295B1QBrm7KocRNc5LLPtWA4hVbUldlZAS"

#-----------------------------------------------------------------------
# create twitter API object
#-----------------------------------------------------------------------

api = twitter.Api(consumer_key,consumer_secret,access_token,access_token_secret, sleep_on_rate_limit=True)

#-----------------------------------------------------------------------
# create twitter API object
#-----------------------------------------------------------------------
CallApiFirst = 0
MaximumCalls = 100000

#-----------------------------------------------------------------------
# Looping through Maximum Calls
#-----------------------------------------------------------------------
while CallApiFirst < MaximumCalls:
###-----------------------------------------------------------------------
### Search Api
###-----------------------------------------------------------------------
    search = api.GetSearch(geocode=[-29.53522956294844, 133.76953125, "2162.719km"], count=500)
    
###-----------------------------------------------------------------------
### create twitter API object
###-----------------------------------------------------------------------
    for tweets in search:
        print(tweets)
        time.sleep(1.05)
        CallApiFirst += 1        
		


